name: gffalign
owner: abims-sbr
homepage_url: https://github.com/eosc-life/D4_marine_eukaryote_genomics_portal
remote_repository_url: https://github.com/abims-sbr/tools-abims/tools/gffalign
description: GFFalign extracts genes coordinates from a whole genome alignment.
long_description: |
        GFFalign extracts genes coordinates from a whole genome alignment.
        This script needs an alignement in TAB format and two gff files.
categories:
- Genome annotation
type: unrestricted
